package mbg.model;

import java.io.Serializable;

public class BittlePicture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle_Picture.Bittle_id
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    private Long bittleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle_Picture.pictures_id
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    private Long picturesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle_Picture.Bittle_id
     *
     * @return the value of Bittle_Picture.Bittle_id
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    public Long getBittleId() {
        return bittleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle_Picture.Bittle_id
     *
     * @param bittleId the value for Bittle_Picture.Bittle_id
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    public void setBittleId(Long bittleId) {
        this.bittleId = bittleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle_Picture.pictures_id
     *
     * @return the value of Bittle_Picture.pictures_id
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    public Long getPicturesId() {
        return picturesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle_Picture.pictures_id
     *
     * @param picturesId the value for Bittle_Picture.pictures_id
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    public void setPicturesId(Long picturesId) {
        this.picturesId = picturesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bittleId=").append(bittleId);
        sb.append(", picturesId=").append(picturesId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}