package mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Bittle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle.id
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle.bitter
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    private Integer bitter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle.message
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle.created_at
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle.latitude
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bittle.longitude
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Bittle
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle.id
     *
     * @return the value of Bittle.id
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle.id
     *
     * @param id the value for Bittle.id
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle.bitter
     *
     * @return the value of Bittle.bitter
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public Integer getBitter() {
        return bitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle.bitter
     *
     * @param bitter the value for Bittle.bitter
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public void setBitter(Integer bitter) {
        this.bitter = bitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle.message
     *
     * @return the value of Bittle.message
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle.message
     *
     * @param message the value for Bittle.message
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle.created_at
     *
     * @return the value of Bittle.created_at
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle.created_at
     *
     * @param createdAt the value for Bittle.created_at
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle.latitude
     *
     * @return the value of Bittle.latitude
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle.latitude
     *
     * @param latitude the value for Bittle.latitude
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bittle.longitude
     *
     * @return the value of Bittle.longitude
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bittle.longitude
     *
     * @param longitude the value for Bittle.longitude
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bitter=").append(bitter);
        sb.append(", message=").append(message);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", latitude=").append(latitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}