package mbg.dao;

import java.util.List;
import mbg.model.Bittle;
import mbg.model.BittleExample;
import org.apache.ibatis.annotations.Param;

public interface BittleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int countByExample(BittleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int deleteByExample(BittleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int insert(Bittle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int insertSelective(Bittle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    List<Bittle> selectByExample(BittleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    Bittle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bittle record, @Param("example") BittleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByExample(@Param("record") Bittle record, @Param("example") BittleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByPrimaryKeySelective(Bittle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByPrimaryKey(Bittle record);
}