package mbg.dao;

import java.util.List;
import mbg.model.BittlePicture;
import mbg.model.BittlePictureExample;
import org.apache.ibatis.annotations.Param;

public interface BittlePictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    int countByExample(BittlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    int deleteByExample(BittlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    int insert(BittlePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    int insertSelective(BittlePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    List<BittlePicture> selectByExample(BittlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") BittlePicture record, @Param("example") BittlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bittle_Picture
     *
     * @mbggenerated Sat Aug 03 23:23:36 CST 2019
     */
    int updateByExample(@Param("record") BittlePicture record, @Param("example") BittlePictureExample example);
}