package mbg.dao;

import java.util.List;
import mbg.model.Bitter;
import mbg.model.BitterExample;
import org.apache.ibatis.annotations.Param;

public interface BitterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int countByExample(BitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int deleteByExample(BitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int insert(Bitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int insertSelective(Bitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    List<Bitter> selectByExample(BitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    Bitter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bitter record, @Param("example") BitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByExample(@Param("record") Bitter record, @Param("example") BitterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByPrimaryKeySelective(Bitter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bitter
     *
     * @mbggenerated Sun Jul 28 13:33:14 CST 2019
     */
    int updateByPrimaryKey(Bitter record);
}